name: Call2 Reusable CI Workflow

on:
  push:
    branches:
      - main

jobs:
  use-reusable-workflow:
    uses: Gee-tha-S/eg1/.github/workflows/blank.yaml@main
    with:
      example_input: 'Hello, world!'
    secrets:
      example_secret: ${{ secrets.EXAMPLE_SECRET }}
